# docker-compose.yml
version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
        # allows data to be persisted
      - "./pgdata:/var/lib/postgresql/data"
